// Proves the RNG port reproduces the C# `Rng` (xorshift128+ / SplitMix64) exactly.
//
// The fixture src/fixtures/rng-reference.json was generated by RUNNING the upstream
// C# Rng (a harness that project-references kindred-resonance's Kindred.Core, with
// no modification to that repo). Each seed records:
//   - doubleBits: BitConverter.DoubleToInt64Bits of the first 20 NextDouble() — an
//     exact bit-for-bit check of the IEEE double, not an epsilon compare.
//   - next1000 / range1to6 / chance50: the first 20 of Next(1000) / Range(1,6) /
//     Chance(50), each from a fresh Rng(seed).
// If any assertion here fails, the port's determinism is broken and the whole
// conformance corpus is meaningless — so this is the first test that must pass.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { Rng } from './engine/rng.ts';

const here = dirname(fileURLToPath(import.meta.url));
interface RngRef {
  seed: string;
  doubleBits: string[];
  next1000: number[];
  range1to6: number[];
  chance50: boolean[];
}
const reference = JSON.parse(readFileSync(join(here, 'fixtures', 'rng-reference.json'), 'utf8')) as RngRef[];

// Bit-exact representation of a JS double, as a signed 64-bit integer (matches
// C#'s BitConverter.DoubleToInt64Bits).
function doubleToInt64Bits(d: number): bigint {
  const buf = new ArrayBuffer(8);
  const view = new DataView(buf);
  view.setFloat64(0, d, true);
  return view.getBigInt64(0, true);
}

test('rng: 8 seeds reproduce the C# NextDouble() bit-for-bit', () => {
  for (const ref of reference) {
    const rng = new Rng(BigInt(ref.seed));
    for (let i = 0; i < ref.doubleBits.length; i++) {
      const bits = doubleToInt64Bits(rng.nextDouble());
      assert.equal(bits.toString(), ref.doubleBits[i], `seed ${ref.seed} double #${i}`);
    }
  }
});

test('rng: Next(1000) matches the C# sequence', () => {
  for (const ref of reference) {
    const rng = new Rng(BigInt(ref.seed));
    for (let i = 0; i < ref.next1000.length; i++) {
      assert.equal(rng.next(1000), ref.next1000[i], `seed ${ref.seed} next #${i}`);
    }
  }
});

test('rng: Range(1,6) matches the C# sequence', () => {
  for (const ref of reference) {
    const rng = new Rng(BigInt(ref.seed));
    for (let i = 0; i < ref.range1to6.length; i++) {
      assert.equal(rng.range(1, 6), ref.range1to6[i], `seed ${ref.seed} range #${i}`);
    }
  }
});

test('rng: Chance(50) matches the C# sequence', () => {
  for (const ref of reference) {
    const rng = new Rng(BigInt(ref.seed));
    for (let i = 0; i < ref.chance50.length; i++) {
      assert.equal(rng.chance(50), ref.chance50[i], `seed ${ref.seed} chance #${i}`);
    }
  }
});

test('rng: the same seed replays identically (determinism)', () => {
  const a = new Rng(1234);
  const b = new Rng(1234);
  for (let i = 0; i < 100; i++) assert.equal(a.nextDouble(), b.nextDouble());
});
